apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-feeder
  labels:
    app: ingress-feeder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingress-feeder
  template:
    metadata:
      labels:
        app: ingress-feeder
    spec:
      serviceAccountName: ingress-feeder
      containers:
      - name: ingress-feeder
        image: hub.docker.com/MYDOCKERSPACE/ingress-feeder
        imagePullPolicy: Always
        env:
        - name: NATS_USER
          valueFrom:
            secretKeyRef:
              name: ingress-feeder
              key: NATS_USER
        - name: NATS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ingress-feeder
              key: NATS_PASSWORD
        - name: NATS_SERVERS
          valueFrom:
            secretKeyRef:
              name: ingress-feeder
              key: NATS_SERVERS
        - name: CF_SITE
          valueFrom:
            secretKeyRef:
              name: ingress-feeder
              key: CF_SITE
        resources:
          requests: {memory: 128Mi, cpu: 50m}
          limits: {memory: 256Mi, cpu: 100m}
