apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ingress-feeder
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ingress-feeder
subjects:
- kind: ServiceAccount
  name: ingress-feeder
